<a href="https://colab.research.google.com/github/Saipatelkuna/neural/blob/main/700757485.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
class Employee:
    employee_count = 0
    total_salary = 0

    def __init__(self, name, family, salary, department):
        self.name = name
        self.family = family
        self.salary = salary
        self.department = department

        Employee.employee_count += 1
        Employee.total_salary += salary

    @classmethod
    def average_salary(cls):
        if cls.employee_count > 0:
            return cls.total_salary / cls.employee_count
        else:
            return 0

class FulltimeEmployee(Employee):
    def __init__(self, name, family, salary, department):
        super().__init__(name, family, salary, department)

employee1 = Employee("Sai", "Kuna", 50000, "HR")
employee2 = FulltimeEmployee("Bala", "Vardhan", 70000, "Finance")
employee3 = Employee("Kiran", "Kumar", 60000, "IT")
employee4 = FulltimeEmployee("Anil", "Aku", 80000, "Marketing")

print("Total number of employees:", Employee.employee_count)

print("Average salary of employees:", Employee.average_salary())


Total number of employees: 4
Average salary of employees: 65000.0


In [7]:
import numpy as np

random_vector = np.random.uniform(1, 15, 20)

reshaped_array = random_vector.reshape(4, 5)

max1_in_rows = reshaped_array.max(axis=1).reshape(-1, 1)
result1_array = np.where(reshaped_array == max1_in_rows, 0, reshaped_array)

print("Original reshaped array:\n", reshaped_array)
print("\nArray after replacing max in each row by 0:\n", result1_array)


Original reshaped array:
 [[ 5.67633953 13.41250963  3.18561608  2.53904857 13.74568414]
 [ 7.59663877  8.22520485 11.73171109 11.51432578  4.91410962]
 [ 4.35687246  2.31177437 14.69065352  2.43015245  1.65476349]
 [ 7.22962688 11.75173011  8.69346601  9.69035986 14.04329914]]

Array after replacing max in each row by 0:
 [[ 5.67633953 13.41250963  3.18561608  2.53904857  0.        ]
 [ 7.59663877  8.22520485  0.         11.51432578  4.91410962]
 [ 4.35687246  2.31177437  0.          2.43015245  1.65476349]
 [ 7.22962688 11.75173011  8.69346601  9.69035986  0.        ]]
